CREATE TABLE CLOTHES
(
    CNO INT PRIMARY KEY,
    CIMG VARCHAR(300) NOT NULL,
    CTEX INT NOT NULL,
    CTYP INT NOT NULL,
    CCOLOR INT NOT NULL
);
CREATE INDEX SORTCNO ON CLOTHES(CNO);

CREATE TABLE USER
(
    UFACETOKEN VARCHAR(100) PRIMARY KEY,
    UIMG VARCHAR(300) NOT NULL,
    USEX ENUM('MALE', 'FEMALE'),
    UNAME VARCHAR(40) NOT NULL,
    UBD DATE,
    UAGE INT
);
CREATE INDEX SORTUSER ON USER(UFACETOKEN ASC, UNAME ASC);

CREATE TABLE UC
(
    CNO INT PRIMARY KEY,
    UFACETOKEN VARCHAR(100) NOT NULL,
    PREFERENCE INT NOT NULL,
    CONSTRAINT USERID FOREIGN KEY(UFACETOKEN) REFERENCES USER(UFACETOKEN),
    CONSTRAINT CLOTHID FOREIGN KEY(CNO) REFERENCES CLOTHES(CNO)
);
CREATE INDEX SORTUC ON UC(UFACETOKEN ASC, PREFERENCE ASC
);

CREATE VIEW PREV(SHOW_CLO, show_user, SHOW_UNM)
AS SELECT CLOTHES.CIMG,USER.UIMG,USER.UNAME 
    FROM CLOTHES,USER,UC
    WHERE CLOTHES.CNO = UC.CNO AND USER.UFACETOKEN = UC.UFACETOKEN;